import type { AlignmentScore } from '@llmagentscore/core';

/**
 * Format alignment score as a Markdown report.
 */
export function formatMarkdown(result: AlignmentScore, sessionId?: string): string {
  const lines: string[] = [];

  lines.push(`# AgentScore Report${sessionId ? ` — ${sessionId}` : ''}`);
  lines.push('');
  lines.push(`**Date:** ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`| Metric | Score |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Overall Alignment | ${result.score}/100 ${getEmoji(result.score)} |`);
  lines.push(`| Truthfulness | ${result.truthfulness}/100 |`);
  lines.push('');

  if (result.matched.length > 0) {
    lines.push(`## ✅ Matched Actions (${result.matched.length})`);
    lines.push('');
    lines.push('| Expected | Actual Tool | Confidence |');
    lines.push('|----------|-------------|------------|');
    for (const m of result.matched) {
      lines.push(
        `| ${m.expected} | \`${m.actual.tool}\` | ${Math.round(m.confidence * 100)}% |`,
      );
    }
    lines.push('');
  }

  if (result.missed.length > 0) {
    lines.push(`## ❌ Missed Actions (${result.missed.length})`);
    lines.push('');
    for (const m of result.missed) {
      lines.push(`- ${m}`);
    }
    lines.push('');
  }

  if (result.unexpected.length > 0) {
    lines.push(`## ⚠️ Unexpected Actions (${result.unexpected.length})`);
    lines.push('');
    for (const u of result.unexpected) {
      lines.push(`- \`${u.tool}\` — ${JSON.stringify(u.params)}`);
    }
    lines.push('');
  }

  if (result.violations.length > 0) {
    lines.push(`## 🚫 Constraint Violations (${result.violations.length})`);
    lines.push('');
    for (const v of result.violations) {
      lines.push(`- ${v.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [AgentScore](https://getagentscore.com)*');

  return lines.join('\n');
}

function getEmoji(score: number): string {
  if (score >= 80) return '✅';
  if (score >= 50) return '⚠️';
  return '❌';
}
